### ISSUE TITLE
how do you get the information from the system

### ISSUE THREAD

**Issue by nkzhimingyuan** [yareally/SignalInfo#3]
Hi, i have readed you source code seriously, but i can't get the way you get the LTE information from the system. so, may know your idea about it? thank you very much

**Comment by yareally** [comment]
See https://github.com/yareally/SignalInfo/blob/scala-experimental/src/com/cc/signalinfo/listeners/SignalListener.scala

Also lines 54 to 61 and 289 to end of file: https://github.com/yareally/SignalInfo/blob/scala-experimental/src/com/cc/signalinfo/activities/MainActivity.scala


Also: https://github.com/android/platform_frameworks_base/blob/master/telephony/java/android/telephony/SignalStrength.java for reference

and http://en.wikipedia.org/wiki/Observer_pattern for how Google makes you fetch it.


Note that the code for my app is in Scala above. The Java version of my app is depreciated and only supporting it now for bug fixes.


Cheers,


Wes

**Comment by nkzhimingyuan** [comment]
first, thank you very much for your help. okay i read your answer. In your project, you created your own  PhoneStateListener to receive the signal strength changed. is that right?

**Comment by yareally** [comment]
You have to. Only way to get the information as it updates.

**Comment by nkzhimingyuan** [comment]
okay. which is the stable branch? i down load the master branch , i find many errors .

**Comment by nkzhimingyuan** [comment]
and i find through the PhoneStateListener(), i can get the SignalStrength, but i can't find function to get LTE  strength from the SignalStrength.  you use the SignalStrength' toString() to get all the information, and deal with it by yourself, is it your way?

**Comment by yareally** [comment]
Yes
