### ISSUE TITLE
Unable to execute DX

### ISSUE THREAD

**Issue by ghost** [yareally/SignalInfo#4]
I have working on building this and have made some progress and as a result of the things I have learned I had to start from scratch a couple of times.  I don’t want to get into the history of what I’ve done, but at this point, I can compile the individual modules but when I build the project I encounter a Dex error (Unable to execute DX).  I believe it has to do with my dependencies and have been carefully examining my settings and trying various options to no avail.  

I’ve had the most difficulty with the dependencies SignalInfo module since I cannot get this module to compile without adding dependencies which are already in the supporting modules and this is what I believe is causing the problem.  However, I cannot figure out how to make SignalInfo happy without these additional modules and am writing as for some guidance with regard to the dependency settings for this app.  I’ve attached a PDF containing my current settings. Thank you.

[settings.pdf](https://github.com/yareally/SignalInfo/files/110649/settings.pdf)

**Comment by yareally** [comment]
Have you reenabled the proguard file you disabled in your previous email? After that, update your proguard. Pretty sure the one that comes with Android is old. If that doesn't work, comment out the lines it's complaining about in the proguard file.

**Comment by ghost** [comment]
I have the latest proguard version:

> java -jar .\Android\sdk\tools\proguard\lib\proguard.jar
> ProGuard, version 5.2.1
> Usage: java proguard.ProGuard [options ...]

Once I enabled Proguard the compile failed:

```
Error:ProGuard: [SignalInfo] Warning: com.google.android.gms.internal.zzih: can't find referenced class android.security.NetworkSecurityPolicy
Error:ProGuard: [SignalInfo] Warning: there were 3 unresolved references to classes or interfaces.
```

It's not clear, to me at least, what I could comment out of the proguard file to potentially resolve this.  As a result, I searched for similar errors via Google and attempted the following:

I added the following lines to proguard-android.txt:
-keep class com.google.android.gms.*\* { _; }
-dontwarn com.google.android.gms._*

Compiled Successfully with 12 Warnings

```
Warning:ProGuard: [SignalInfo] Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [android-support-v7-gridlayout.jar:META-INF/MANIFEST.MF])
```

Attempted to run the app . .  It crashes

```
01-31 08:46:09.188  18549-18549/com.cc.signalinfo I/art? Late-enabling -Xcheck:jni
01-31 08:46:09.349  18549-18549/com.cc.signalinfo W/Ads? Required XML attribute "adSize" was missing.
01-31 08:46:09.402  18549-18549/com.cc.signalinfo D/AndroidRuntime? Shutting down VM
01-31 08:46:09.403  18549-18549/com.cc.signalinfo E/AndroidRuntime? FATAL EXCEPTION: main
```

So then, in radio_signal_fragment.xml I changed
    xmlns:ads="http://schemas.android.com/apk/lib/com.google.ads"
To:
    xmlns:ads="http://schemas.android.com/apk/res-auto"

Compiled successfully with 14 warnings

```
Warning:ProGuard: [SignalInfo] Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [android-support-v7-gridlayout.jar:META-INF/MANIFEST.MF])
```

Attempted to run the app . .  It crashes

```
01-31 08:51:20.935  21251-21251/com.cc.signalinfo I/art? Late-enabling -Xcheck:jni
01-31 08:51:21.163  21251-21251/com.cc.signalinfo W/Bundle? Key com.google.android.gms.version expected Integer but value was a java.lang.String.  The default value 0 was returned.
01-31 08:51:21.166  21251-21251/com.cc.signalinfo W/Bundle? Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
```

This is where I am currently stuck.  I feel that I may be going in circles here as it's not clear if I'm actually resolving anything or creating new problems for my self.   I've attached my config files for reference
[intelliJ-Android.zip](https://github.com/yareally/SignalInfo/files/111314/intelliJ-Android.zip)
.

**Comment by yareally** [comment]
Remove all the ad stuff. Should work then

**Comment by ghost** [comment]
Yes - that did it.  Thank you.

**Comment by yareally** [comment]
No problem. Glad you got it to work.
